export enum AppRoutes {
  LOGIN = "/login",
  REGISTER = "/register",
  HOME = "/",
  PROFILE = "/profile",
  EVENT_DETAILS = "/events/:id",
  NOT_FOUND = "*",
  EVENT_CREATE = "/events/new",
  EVENT_UPDATE = "/events/:id/edit",
  EVENT_VIEW = "/events/:id/view",
  MAP = "/map",
  FRIENDS = "/friends",
  FRIEND_PROFILE = "/users/:id",
  FRIEND_REQUESTS = "/friends/requests",
  FRIEND_LIST = "/friends/list",
}
